jakarta.persistence.jdbc.driver=com.mysql.cj.jdbc.Driver
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/dyashin_sql
jakarta.persistence.jdbc.user=root
jakarta.persistence.jdbc.password=admin@123
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false 