#================Mysql Database==================
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/dyashin_sql
jakarta.persistence.jdbc.user=root
jakarta.persistence.jdbc.password=admin@123
jakarta.persistence.jdbc.driver=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true

#================PostgreSQL Database==================
#jakarta.persistence.jdbc.url=jdbc:postgresql://localhost:5432/dyasin_sql
#jakarta.persistence.jdbc.user=postgres
#jakarta.persistence.jdbc.password=root
#jakarta.persistence.jdbc.driver=org.postgresql.Driver
#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#hibernate.hbm2ddl.auto=update
#hibernate.show_sql=true

